In [1]:
me = {'height' : 180}

print(me['height'])

180


In [2]:
size = 10
## 0 ~ size-1
for i in range(size):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
class MAN:
    def __init__(self, name):
        self.name = name
        print("Initialized")
    
    def hello(self):
        print("Hello"+self.name)
    
    def goodbye(self):
        print("Good-bye")

In [4]:
m = MAN("David")
m.hello()

Initialized
HelloDavid


In [1]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,2]])

In [6]:
print(A)
A.shape

[[1 2]
 [3 2]]


(2, 2)

In [7]:
#Broadcasting
A = np.array([[1,2],[3,5]])
B = np.array([10,20])

In [8]:
print(A*B)

[[ 10  40]
 [ 30 100]]


In [14]:
X = np.array([[51,55],[14,19],[0,4]])
X = X.flatten()

In [15]:
print(X)

[51 55 14 19  0  4]


In [16]:
X[[0,2,4]]

array([51, 14,  0])